version: "3.4"
services:
  app:
    build:
      context: ./
    volumes:
      - "./:/app"
    ports:
      - "8501:8501"
    image: app-chatbot
    hostname: chatbot
    container_name: chatbot
    restart: always
